apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node2-deployment
  namespace: app-dev
  labels:
    app: node-app2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-app2
    spec:
      containers:
      - name: node-app2
        image: nilesh7756/node-web-app2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
